# Tasks
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@parentPath = api/tasks
@taskId = 1
@deleteTaskId = 4
@contentType = application/json

# Create a new task
POST {{host}}/{{parentPath}}/ HTTP/1.1
Content-Type: {{contentType}}

{
  "title": "Новаое задание",
  "description": "Забить гвоздь",
  "price": 100,
  "image": "https://images/picture.jpeg",
  "address": "Задний проход",
  "tags": [1],
  "city": "Москва",
  "categories": [1],
  "responses": [1],
  "comments": [1],
  "status": "New",
  "userId": "25"
}

###

# Get task by ID
GET {{host}}/{{parentPath}}/{{taskId}} HTTP/1.1

###

# Delete task by id
DELETE  {{host}}/{{parentPath}}/{{deleteTaskId}} HTTP/1.1
Content-Type: {{contentType}}

###

# Get all tasks
GET {{host}}/{{parentPath}}/ HTTP/1.1

###

# Update task
PATCH {{host}}/{{parentPath}}/{{taskId}} HTTP/1.1
Content-Type: application/json

{
  "title": "Старое задание"
}

###
