# Users
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@parentPath = api/auth
@userId = 64f8b4dc72d5502a44680895
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGY3YjRmZjNiMWY5MTU2NDYxOTk4NWQiLCJlbWFpbCI6ImV4ZWN1dG9yQG1haWwucnUiLCJyb2xlIjoiZXhlY3V0b3IiLCJuYW1lIjoiYm9iIiwiaWF0IjoxNjk0MDIwMDMyLCJleHAiOjE2OTQyNzkyMzJ9.RZvuH3Raw1h-SWl7jX-CyRhfpWk4hE0ow6FvrQY4cGM
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU3Yzg1OGFkMmUwYjA1ODExY2Q0Y2IiLCJlbWFpbCI6InVzZXJAbWFpbC5ydSIsInJvbGUiOiJjdXN0b21lciIsIm5hbWUiOiJCb2Jpbmluc2tpeSBCb2IiLCJ0b2tlbklkIjoiYTAwMmQyMmYtZTBhMi00NjQ1LThjNzItZDVhY2UzMTczNTJhIiwiaWF0IjoxNjkyOTExNzE2LCJleHAiOjE2OTU1MDM3MTZ9.TNY3Jzm4Js-qdULBaGgmyfr4NGKFtucys7cKEeit0Lw
@contentType = application/json

# Create a new user
POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "bob",
  "email": "cus@mail.ru",
  "city": "Москва",
  "password": "123456",
  "role": "customer",
  "avatar": "https://images/avatarka.jpeg",
  "dateOfBirth": "1995-01-01",
  "personalInfo": "Плачу много",
  "specialization": ["Каменщик", "Каменщик"]
}

###

# Get user by ID
GET {{host}}/{{parentPath}}/{{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Login user by email and password
POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "cus@mail.ru",
  "password": "123456"
}

###

# Get new JWT pair
POST {{host}}/{{parentPath}}/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###

# Check user token
POST {{host}}/{{parentPath}}/check HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Change user password
PATCH {{host}}/{{parentPath}}/changePassword HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "email": "user@mail.ru",
  "currentPassword": "qwerty",
  "newPassword": "123456"
}

###

# Update user
PATCH {{host}}/{{parentPath}}/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "role": "costumer"
}

###

# Get users
POST {{host}}/{{parentPath}}/usersList HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "ids": ["64ed23f77b97919bf848281c", "64ed24a9640ee76d06fdbd1e", "64ed24faca853b6640463eab"]
}

###
