# Users
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@parentPath = api/auth
@userId = 64ed25fc1912012fa97c865c
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGVkMjNmNzdiOTc5MTliZjg0ODI4MWMiLCJlbWFpbCI6InVzZXJAbWFpbC5ydSIsInJvbGUiOiJjdXN0b21lciIsIm5hbWUiOiJib2IiLCJpYXQiOjE2OTMyNjI4NTEsImV4cCI6MTY5MzUyMjA1MX0.01iK_3sNmwkikkgweoHx-wbCL7Qh7IIkTz2fUTeViVg
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU3Yzg1OGFkMmUwYjA1ODExY2Q0Y2IiLCJlbWFpbCI6InVzZXJAbWFpbC5ydSIsInJvbGUiOiJjdXN0b21lciIsIm5hbWUiOiJCb2Jpbmluc2tpeSBCb2IiLCJ0b2tlbklkIjoiYTAwMmQyMmYtZTBhMi00NjQ1LThjNzItZDVhY2UzMTczNTJhIiwiaWF0IjoxNjkyOTExNzE2LCJleHAiOjE2OTU1MDM3MTZ9.TNY3Jzm4Js-qdULBaGgmyfr4NGKFtucys7cKEeit0Lw
@contentType = application/json

# Create a new user
POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "bob",
  "email": "executor@mail.ru",
  "city": "Москва",
  "password": "qwerty",
  "role": "executor",
  "avatar": "https://images/avatarka.jpeg",
  "dateOfBirth": "1991-01-01",
  "personalInfo": "Плачу много"
}

###

# Get user by ID
GET {{host}}/{{parentPath}}/{{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Login user by email and password
POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "user@mail.ru",
  "password": "qwerty"
}

###

# Get new JWT pair
POST {{host}}/{{parentPath}}/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###

# Check user token
POST {{host}}/{{parentPath}}/check HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Change user password
PATCH {{host}}/{{parentPath}}/changePassword HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "email": "user@mail.ru",
  "currentPassword": "qwerty",
  "newPassword": "123456"
}

###

# Update user
PATCH {{host}}/{{parentPath}}/{{userId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "name": "Jim"
}

###

# Get users
POST {{host}}/{{parentPath}}/usersList HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "ids": ["64ed23f77b97919bf848281c", "64ed24a9640ee76d06fdbd1e", "64ed24faca853b6640463eab"]
}

###
