# Tasks
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@parentPath = api/comments
@commentId = 275a4b5b-e3d3-4411-8e4f-3594fd5f6108
@deleteCommentId = 2ecec575-45bd-4298-bb49-1658c6e1860d
@contentType = application/json

# Create a new comment
POST {{host}}/{{parentPath}}/create HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "good job",
  "taskId": "fsdal;fad5f1s3da553asd4fsad"
}

###

# Get comment by ID
GET {{host}}/{{parentPath}}/{{commentId}} HTTP/1.1

###

# Delete comment by id
DELETE  {{host}}/{{parentPath}}/{{deleteCommentId}} HTTP/1.1
Content-Type: {{contentType}}

###
